export const TYPES = {
    Bot: Symbol("Bot"),
    Client: Symbol("Client"),
    MessageHandlerService: Symbol("MessageHandlerService"),
    MessageBroker: Symbol("MessageBroker"),
    MappedResponder: Symbol("MappedResponder"),
    ResponseMap: Symbol("ResponseMap"),
    StretchScheduledMessenger: Symbol("StretchScheduledMessenger"),
    ScheduledMessengerService: Symbol("ScheduledMessengerService"),
    AppSettings: Symbol("AppSettings"),
    LoggingService: Symbol("LoggingService"),
    Log: Symbol("Log"),
    DbService: Symbol("DbService"),
    BotRepository: Symbol("BotRepository"),
    SlashCommandService: Symbol("SlashCommandService"),
    ReminderCommand: Symbol("ReminderCommand"),
};
